server:
  port: 8910

spring:
  main:
    allow-bean-definition-overriding: true

rocketmq:
  env: local_
  name-server: 172.16.10.45:9876;172.16.10.46:9876
  producer:
    group: ooxx_producer
  consumer:
    local:
      group: local
      topic: ooxx
      tag: xxoo